In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential   ## sequential will generate a linear stack of layes
from tensorflow.keras.layers import Dense        ## layes (dense) will create a fully connected network , each input is connected to each neuron)
from sklearn.datasets import load_iris           ## This is the data set which we are loading
from sklearn.model_selection import train_test_split   ## model selection for spilliting
from sklearn.preprocessing import StandardScaler, LabelBinarizer  ## preprocessing is required for one hot encoding and standardisation for mean 0 and SD1
import numpy as np
import matplotlib.pyplot as plt
from keras.layers import Dropout
from keras.regularizers import l2


In [ ]:
iris = load_iris()
X = iris.data  # shape: (150, 4)
y = iris.target  # shape: (150,)
print(X, y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
encoder = LabelBinarizer() ## inititalzes the one hot encoding
y_encoded = encoder.fit_transform(y) ## converts the y labels into one hot encoding , for cross entropy loss function


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)  ## fit_transform to understand the mean and SD and then stardardize
X_test = scaler.transform(X_test)   ## only transform is to use the X_train data mean and SD for standardisation


In [ ]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],), kernel_regularizer=l2(0.01)),
    Dropout(0.3),
    Dense(64, activation='relu', kernel_regularizer=l2(0.01)),
    Dropout(0.3),
    Dense(3, activation='softmax')
])


In [ ]:
model.compile(
    optimizer='adam',  ## uses dynamic learning rate and momentom
    loss='categorical_crossentropy', ## for multiclass classification
    metrics=['accuracy']
)


In [ ]:
model.fit(X_train, y_train, epochs=50, batch_size=8, validation_split=0.1, verbose=1)


Epoch 1/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.5699 - loss: 1.6621 - val_accuracy: 0.5833 - val_loss: 1.5338
Epoch 2/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6401 - loss: 1.4631 - val_accuracy: 0.6667 - val_loss: 1.3684
Epoch 3/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7218 - loss: 1.2450 - val_accuracy: 0.6667 - val_loss: 1.2358
Epoch 4/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8075 - loss: 1.0851 - val_accuracy: 0.7500 - val_loss: 1.1363
Epoch 5/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8149 - loss: 1.0009 - val_accuracy: 0.8333 - val_loss: 1.0561
Epoch 6/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7767 - loss: 0.9469 - val_accuracy: 0.8333 - val_loss: 0.9985
Epoch 7/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.9270 - val_accuracy: 0.8333 - val_loss: 0.9378
Epoch 8/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8775 - loss: 0.7741 - val_accuracy: 0.8333 - val_loss

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.0242
Test Accuracy: 1.00
